
replicaCount: 1
image:
    repository: mihacloud/1721488291
    tag: latest

namespace: default-namespace

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
    type: ClusterIP
    port: 80
    targetPort: 3000
    annotations: {}

ingress:
    enabled: true
    annotations: 
        kubernetes.io/ingress.class: nginx
    hosts:
        - host: 1721488291.miha.cloud
          paths: 
            - path: /
              pathType: ImplementationSpecific
    tls: []

resources: {}

livenessProbe:
httpGet:
    path: /
    port: http
readinessProbe:
httpGet:
    path: /
    port: http

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
                        