
replicaCount: 1
namespace: ef855cef-1a01-4c30-9ba5-2ddef0b1e17b
service: s-ef855cef-1a01-4c30-9ba5-2ddef0b1e17b
name: miha-1721754421
image:
    repository: mihacloud/1721754421
    tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
    annotations: {}

ingress:
    enabled: true
    className: "nginx"
    annotations: 
        kubernetes.io/ingress.class: nginx
    hosts:
        - host: 1721754421.miha-clound.com
          paths: 
            - path: /
              pathType: ImplementationSpecific
    tls: []

resources: {}

livenessProbe:
    httpGet:
        path: /
        port: http

readinessProbe:
    httpGet:
        path: /
        port: http

autoscaling:
    enabled: true
    min: 1
    max: 2
    targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
                        